[xammactests] RetrievePeripherals on macOS is complaining
```
ObjCRuntime.RuntimeException: Failed to marshal the Objective-C object 0x7ff62ff227f0 (type: MonoTouchFixtures_CoreBluetooth_CBCentralManagerTest_ManagerDelegate). Could not find an existing managed instance for this object, nor was it possible to create a new managed instance (because the type 'MonoTouchFixtures.CoreBluetooth.CBCentralManagerTest+ManagerDelegate' does not have a constructor that takes one IntPtr argument).
```

Therefore, add the `IntPtr` `.ctor`
(Note: I cannot reproduce locally so I'm eyeballing this)