Revert "[runtime] Fix the executable name we use for embedded. (#2095)"
This reverts commit 425274ac2fd0ba98aa68fcc9cbcb9e063bff8637.

Prevents building xcode9 branch, see: https://jenkins.mono-project.com/job/xamarin-macios-pr-builder/3886/console

```
runtime.m:1122:9: error: cannot initialize a variable of type 'char *' with an rvalue of type 'const char *'
                  char *last_sep = strrchr (info.dli_fname, '/');
```