[net7.0] Update dependencies from dotnet/installer (#14650)
* Update dependencies from https://github.com/dotnet/installer build 20220404.1

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.4.22204.1

Dependency coherency updates

Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref
 From Version 7.0.0-preview.4.22181.10 -> To Version 7.0.0-preview.4.22201.3 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220405.16

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.4.22205.16

Dependency coherency updates

Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref
 From Version 7.0.0-preview.4.22181.10 -> To Version 7.0.0-preview.4.22205.1 (parent: Microsoft.Dotnet.Sdk.Internal

* [tests] Remove dead code.

* Update dependencies from https://github.com/dotnet/installer build 20220407.2

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.4.22207.2

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22206.2 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220407.24

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.4.22207.24

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22206.2 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220408.2

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.4.22208.2

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22206.2 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220411.1

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.4.22211.1

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22208.1 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220412.1

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.4.22212.1

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22211.1 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220412.35

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.4.22212.35

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22211.1 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220414.1

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.4.22214.1

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22211.1 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220414.17

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.4.22214.17

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22211.1 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220415.7

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.4.22215.7

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22211.1 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220417.3

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.4.22217.3

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22211.1 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220418.29

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.4.22218.29

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22213.2 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220419.19

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.4.22219.19

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22213.2 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220420.23

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.5.22220.23

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22213.2 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220421.9

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.5.22221.9

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22213.2 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220425.1

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.5.22225.1

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22213.2 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220427.1

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.5.22227.1

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22226.2 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220427.8

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.5.22227.8

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22227.1 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220428.6

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.5.22228.6

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22227.1 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220429.2

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.5.22229.2

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22228.1 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220503.34

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.5.22253.34

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22228.1 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220505.1

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.5.22255.1

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22228.1 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220506.2

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.5.22256.2

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22228.1 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220506.8

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.5.22256.8

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22228.1 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220507.3

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.5.22257.3

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22228.1 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220508.1

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.5.22258.1

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22228.1 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220510.3

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.5.22260.3

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22259.1 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220510.20

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.5.22260.20

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22259.1 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220511.8

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.5.22261.8

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22259.1 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220512.14

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.5.22262.14

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22259.1 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220513.22

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.5.22263.22

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22259.1 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220517.11

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.5.22267.11

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22266.1 (parent: Microsoft.Dotnet.Sdk.Internal

* Attempt workaround for https://github.com/dotnet/linker/issues/2759

* [runtime] Skip passing ICU_DAT_FILE_PATH to the runtime if we don't have an ICU data file.

* [dotnet] Write our own code for the global using for nfloat.

This way we can ignore this compiler warning:

    The type name 'nfloat' only contains lower-cased ascii characters. Such names may become reserved for the language.

* Update dependencies from https://github.com/dotnet/installer build 20220523.1

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.5.22273.1

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22270.1 (parent: Microsoft.Dotnet.Sdk.Internal

* Revert "Attempt workaround for https://github.com/dotnet/linker/issues/2759"

This reverts commit 865055690491329defc2a3eedd0cd0fa18d1e241.

* [src] Fix computing the value type size of System.UIntPtr.

* Why is this needed?

> SpriteKit/SKNode.cs(89,29): error CS0121: The call is ambiguous between the following methods or properties: 'NSMutableSet<TKey>.NSMutableSet(NativeHandle)' and 'NSMutableSet<TKey>.NSMutableSet(nint)'

* Update dependencies from https://github.com/dotnet/installer build 20220524.1

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.5.22274.1

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22273.1 (parent: Microsoft.Dotnet.Sdk.Internal

* Update dependencies from https://github.com/dotnet/installer build 20220524.9

Microsoft.Dotnet.Sdk.Internal
 From Version 7.0.100-preview.4.22201.11 -> To Version 7.0.100-preview.5.22274.9

Dependency coherency updates

Microsoft.NET.ILLink.Tasks,Microsoft.AspNetCore.App.Ref,Microsoft.NETCore.App.Ref,Microsoft.NET.Workload.Emscripten.Manifest-7.0.100
 From Version 7.0.100-1.22178.1 -> To Version 7.0.100-1.22273.1 (parent: Microsoft.Dotnet.Sdk.Internal

Co-authored-by: dotnet-maestro[bot] <dotnet-maestro[bot]@users.noreply.github.com>
Co-authored-by: Rolf Bjarne Kvinge <rolf@xamarin.com>