[release/7.0.1xx-rc2] [dotnet] Don't try to ILStrip assemblies unless we're connected to a Mac. (#16161)
Fixes this error:

targets/Xamarin.Shared.Sdk.targets(754,3): error MSB4018: The
"Xamarin.MacDev.Tasks.ILStrip" task failed unexpectedly.
targets/Xamarin.Shared.Sdk.targets(754,3): error MSB4018:
System.ArgumentException: 'Assemblies' is required. (Parameter
'Assemblies')
targets/Xamarin.Shared.Sdk.targets(754,3): error MSB4018: at
ILStrip.Execute()
targets/Xamarin.Shared.Sdk.targets(754,3): error MSB4018: at
ILStripTasks.ILStripBase.Execute() in
/Users/rolf/work/maccore/main/xamarin-macios/msbuild/Xamarin.iOS.Tasks/Tasks/ILStripBase.cs:line
18
targets/Xamarin.Shared.Sdk.targets(754,3): error MSB4018: at
Xamarin.MacDev.Tasks.ILStrip.Execute() in
/Users/rolf/work/maccore/main/xamarin-macios/msbuild/Xamarin.iOS.Tasks/Tasks/ILStrip.cs:line
16
targets/Xamarin.Shared.Sdk.targets(754,3): error MSB4018: at
Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
targets/Xamarin.Shared.Sdk.targets(754,3): error MSB4018: at
Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost
taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost
taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
     0 Warning(s)
     1 Error(s)


Backport of #16160

Co-authored-by: Rolf Bjarne Kvinge <rolf@xamarin.com>