[msbuild] Execute the '_CreateBindingResourcePackage' target on Windows when bundling original resources.
Otherwise the binding resource package isn't created, because no library
projects are built remotely when bundling original resources.

Fixes this error in the BundleStructureWithRemoteMac test:

    Errors
        D:\AzDO\_work\16\s\xamarin-macios\tests\dotnet\Windows\bin\dotnet\packs\Microsoft.iOS.Sdk.net10.0_18.2\18.2.10345-ci.pr.gh22105\targets\Xamarin.Shared.Sdk.targets(1655,3): clang++ exited with code 1:
    Undefined symbols for architecture arm64:
      "_theUltimateAnswer", referenced from:
          <initial-undefines>
    ld: symbol(s) not found for architecture arm64
    clang++: error: linker command failed with exit code 1 (use -v to see invocation) [d:\AzDO\_work\16\s\xamarin-macios\tests\dotnet\BundleStructure\iOS\BundleStructure.csproj]