[catalyst] Remove more framework that are not available on catalyst (#10678)
Follow up to https://github.com/xamarin/xamarin-macios/pull/10658

This includes a `.ctor` chaining fix for the forwarder tool which
resulted in several errors like:

```
build/dotnet/maccatalyst/ref/Xamarin.iOS.cs(12640,17): error CS1729: 'UIScene' does not contain a constructor that takes 0 arguments
```

There's two different issues blocking ARKit and AddressBookUI that
will be solved in different PR.

When used with Xamarin.MacCatalyst we must still consider Xamarin.iOS.dll
as a platform assembly (and not user code) so the linker will remove more
code (that usual).

This is even more important as the stubs are unusable - so we do not want
to keep any extra pieces there since they would not work anyway.