[src] Reference the attribute dll from the build/ directory instead of the installed version.
This fixes a random build failure (due to parallel make):

```
error CS0006: Metadata file `/Users/marek/git/my/xamarin-macios/_mac-build/Library/Frameworks/Xamarin.Mac.framework/Versions/Current/lib/bgen/Xamarin.Mac-mobile.BindingAttributes.dll' could not be found
Compilation failed: 1 error(s), 0 warnings
bgen: API binding contains errors.
make[1]: *** [build/mac/mobile/generated-sources] Error 1
```