[Foundation] Fix code to not cause a potential null error when compiling using the .NET 5 BCL.
Fix code to not cause a potential null reference error from csc when compiling
using the .NET 5 BCL:

> Foundation/DictionaryContainer.cs(330,47): error CS8604: Possible null reference argument for parameter 'source' in 'IEnumerable<NSObject> Enumerable.Select<T, NSObject>(IEnumerable<T> source, Func<T, NSObject> selector)'.

And do so by rewriting Linq code, which also makes the code much less memory
hungry and more performant.