[src] Add the NativeName attribute to the NMatrix4 struct so that P/Invoke wrappers are correctly generated.
Also revert previous fix attempt.

Fixes this test failure:

    Xamarin.Tests.DotNetProjectTest.PInvokeWrapperGenerator(MacOSX,"osx-arm64"): 'dotnet build' failed with exit code 1
    Full command: /Users/builder/azdo/_work/2/s/xamarin-macios/builds/downloads/dotnet-sdk-8.0.101-servicing.23565.7/dotnet build /Users/builder/azdo/_work/2/s/xamarin-macios/tests/dotnet/MySimpleApp/macOS/MySimpleApp.csproj /p:_BundlerVerbosity=1 /p:RuntimeIdentifier=osx-arm64 "/p:MonoBundlingExtraArgs=--require-pinvoke-wrappers:true --registrar:static" "/p:MtouchExtraArgs=--require-pinvoke-wrappers:true --registrar:static" /bl:/Users/builder/azdo/_work/2/s/xamarin-macios/tests/dotnet/MySimpleApp/macOS/log-build-20231206_145951.binlog /v:diag /consoleloggerparameters:Verbosity=Quiet
    Listing first 1 error(s) (of 1 error(s)):
    /Users/builder/azdo/_work/2/s/xamarin-macios/builds/downloads/dotnet-sdk-8.0.101-servicing.23565.7/packs/Microsoft.macOS.Sdk/14.0.8597-ci.pr.gh19412/targets/Xamarin.Shared.Sdk.targets(1412): error: clang exited with code 1:
    /Users/builder/azdo/_work/2/s/xamarin-macios/tests/dotnet/MySimpleApp/macOS/obj/Debug/net8.0-macos/osx-arm64/linker-cache/pinvokes.mm:37233:151: error: unknown type name 'NMatrix4'
    typedef unsigned char(*func_xamarin_pinvoke_wrapper_bool_objc_msgSend_out_NMatrix4_NativeHandle_ref_NativeHandle) (void * receiver, void * selector, NMatrix4* arg1, void * arg2, void ** arg3);
    ^
    /Users/builder/azdo/_work/2/s/xamarin-macios/tests/dotnet/MySimpleApp/macOS/obj/Debug/net8.0-macos/osx-arm64/linker-cache/pinvokes.mm:37235:122: error: unknown type name 'NMatrix4'
    xamarin_pinvoke_wrapper_bool_objc_msgSend_out_NMatrix4_NativeHandle_ref_NativeHandle (void * receiver, void * selector, NMatrix4* arg1, void * arg2, void ** arg3)