Set maximum mono version to the Cycle 8 mono version. (#1118)
This fixes mmp tests that fail when a Cycle 9 mono version is installed on the bots:

```
		Undefined symbols for architecture i386:
		  "_mono_btls_bio_flush", referenced from:
		     -u command line option
		[...]
		ld: symbol(s) not found for architecture i386
		clang: error: linker command failed with exit code 1 (use -v to see invocation)
MMP: error MM5109: Native linking failed with error code 1.  Check build log for details.
	Task "Mmp" execution -- FAILED
	Done building target "_CompileToNative" in project "/Users/builder/data/lanes/3969/1d0df24f/source/xamarin-macios/tests/mmptest/regression/system-mono/system-mono.csproj".-- FAILED
Done building project "/Users/builder/data/lanes/3969/1d0df24f/source/xamarin-macios/tests/mmptest/regression/system-mono/system-mono.csproj".-- FAILED
```