[siminstaller] Convert to .NET project.
In addition to being good by itself, by fixing all the resulting nullability
warnings, this random problem goes away:

    Unhandled Exception:
    System.NullReferenceException: Object reference not set to an instance of an object
      at xsiminstaller.MainClass.Main (System.String[] args) [0x006ca] in /Users/builder/azdo/_work/4/s/xamarin-macios/tools/siminstaller/Program.cs:228
    [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
      at xsiminstaller.MainClass.Main (System.String[] args) [0x006ca] in /Users/builder/azdo/_work/4/s/xamarin-macios/tools/siminstaller/Program.cs:228