[arkit] Fixes based on comments
- Fixed the generator to avoid `ARKit/ARSCNViewDelegate.g.cs(189,43): error CS0432: Alias 'Iglobal' not found`
- ARPointCloud can be tested with this samples: https://www.dropbox.com/s/0xlz0sdzjj4507s/ARPointCloudTest.zip?dl=0
  It requires deploying on devices and moving the camera around so ARKit can return some points. After 5 seconds it should
  print the points.
- Fixed styling.
- Added missing simd.
- Fixed intro tests.

Note: not having [Model] on ARSessionObserver got us:

```
[FAIL] iOSApiProtocolTest.ApiProtocolTest.GeneralCase : 1 types do not really conform to the protocol interfaces
[FAIL] Could not load ARKit.ARSessionObserver

          at Introspection.ApiBaseTest.AssertIfErrors (System.String s, System.Object[] parameters) [0x00054] in /Users/vidondai/Documents/xi-xcode9/xamarin-macios/tests/introspection/ApiBaseTest.cs:143
          at Introspection.ApiProtocolTest.GeneralCase () [0x001ec] in /Users/vidondai/Documents/xi-xcode9/xamarin-macios/tests/introspection/ApiProtocolTest.cs:342
          at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
          at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in /Users/vidondai/Documents/xi-xcode9/xamarin-macios/external/mono/mcs/class/corlib/System.Reflection/MonoMethod.cs:305
```